service: Auto-Scheduling
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  CheckCandidate:
    handler: src/handler.checkCandidateAvailability

  ScheduleInterview:
    handler: src/handler.scheduleInterview

  AddCandidate:
    handler: src/handler.addCandidate

stepFunctions:
  stateMachines:
    InterviewAutoScheduling:
      name: InterviewAutoScheduling
      definition:
        Comment: "Auto scheduling of an interview"
        StartAt: CheckCandidate
        States:
          CheckCandidate:
            Type: Task
            Resource:
              Fn::GetAtt: [CheckCandidate, Arn]
            Next: EvaluateCandidateCount

          EvaluateCandidateCount:
            Type: Choice
            Choices:
              - Variable: "$.count"
                NumericGreaterThan: 0
                Next: ScheduleInterview
              - Variable: "$.count"
                NumericEquals: 0
                Next: AddCandidate
            Default: EndWorkflow

          ScheduleInterview:
            Type: Task
            Resource:
              Fn::GetAtt: [ScheduleInterview, Arn]
            Next: EndWorkflow

          AddCandidate:
            Type: Task
            Resource:
              Fn::GetAtt: [AddCandidate, Arn]
            Next: EndWorkflow

          EndWorkflow:
            Type: Pass
            End: true

plugins:
  - serverless-step-functions
